public enum Type {
    
    ANTIBIOTIC, VACCINE, PARASITICIDE, ANALGESIC, VITAMIN_SUPPLEMENT, 
    DOG_FOOD,CAT_FOOD, BIRD_FOOD, FISH_FOOD, 
    PET_TREATS,CATTLE_FEED, POULTRY_FEED, PIG_FEED, HORSE_FEED,
    COLLAR, LEASH, FEEDER, PET_BED, PET_TOY,  
    SEEDS, FERTILIZER, PESTICIDE, AGRO_TOOLS,  PET_SHAMPOO, 
    DISINFECTANT, FLEA_CONTROL;
}
